Update study.yml

diff --git a/.github/workflows/study.yml b/.github/workflows/study.yml
--- a/.github/workflows/study.yml
+++ b/.github/workflows/study.yml
@@ -5,18 +5,68 @@ on:
   pull_request:
     branches: [ "main" ]
   workflow_dispatch:
+
+permissions:
+  contents: read
   
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: show files
-        run: ls
+      - name: install JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+
+
+      - name: Build with Maven
+        run: ./mvnw clean package -Dtestskip
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME}}
+          password: ${{ secrets.DOCKERHUB_TOKEN}}
+
+      - name: Build Docker
+        run: docker build --platform linux/amd64 -t ${{secrets.DOCKERHUB_USERNAME}}/server .
+      - name: Push Docker
+        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/server:latest
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set target IP
+      - run: 
+        CURRENT_UPSTREAM=$(curl -s "http://%{{ secrets.NGINX_IP }}/env")
+        echo $CURRENT_UPSTREAM
+        if [ $CURRENT_UPSTREAM -ne blue -o $CURRENT_UPSTREAM -ne green ]; then
+          $CURRENT_UPSTREAM=blue
+        fi
+        if [ $CURRENT_UPSTREAM -eq blue]; then
+          echo "CURRENT_ip=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
+          echo "STOPPED_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
+          echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+        elif [ $CURRENT_UPSTREAM -eq green]; then
+          echo "CURRENT_ip=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
+          echo "STOPPED_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
+          echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV     
+        else
+          echo "error"
+          exit 1
+        fi
+      - name: Docker compose
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ env.STOPPED_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script:
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
+            docker-compose up -d
+
         
-      - name: print hello
-        run: echo hello
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
